/* The following code was generated by JFlex 1.4.3 on 27/05/26, 11:07 p.m. */

package codigo;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/05/26, 11:07 p.m. from the specification file
 * <tt>src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\2\0\1\3\22\0\1\3\6\0\1\5\1\36"+
    "\1\40\2\0\1\3\1\37\2\0\12\2\7\0\32\1\4\0\1\26"+
    "\1\0\1\11\1\30\1\33\1\10\1\14\1\32\1\16\1\1\1\7"+
    "\1\27\1\1\1\25\1\12\1\13\1\22\1\17\1\34\1\15\1\23"+
    "\1\21\1\20\1\6\1\1\1\24\1\31\1\35\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\17\2"+
    "\1\1\23\2\1\7\2\2\1\0\10\2\1\10\11\2"+
    "\1\11\3\2\1\12\1\2\1\0\21\2\1\13\3\2"+
    "\1\3\1\2\1\14\5\2\1\14\1\15\1\2\1\16"+
    "\1\2\1\17\1\2\1\20\10\2\1\21\7\2\1\22"+
    "\3\2\1\23\34\2\1\24\4\2\1\25\3\2\1\26"+
    "\3\2\1\27\1\30\4\2\1\31\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\41\0\41\0\245"+
    "\0\306\0\347\0\u0108\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad"+
    "\0\u01ce\0\u01ef\0\u0210\0\u0231\0\u0252\0\u0273\0\u0294\0\u02b5"+
    "\0\u02d6\0\u02f7\0\u0318\0\u0339\0\u035a\0\u037b\0\u039c\0\u03bd"+
    "\0\u03de\0\u03ff\0\u0420\0\u0441\0\u0462\0\u0483\0\u04a4\0\u04c5"+
    "\0\u04e6\0\u0507\0\102\0\u0528\0\u0549\0\u056a\0\u058b\0\u05ac"+
    "\0\u05cd\0\u05ee\0\u060f\0\u0630\0\u0651\0\u0672\0\102\0\u0693"+
    "\0\u06b4\0\u06d5\0\u06f6\0\u0717\0\u0738\0\u0759\0\u077a\0\u079b"+
    "\0\102\0\u07bc\0\u07dd\0\u07fe\0\u081f\0\u0840\0\u0861\0\u0882"+
    "\0\u08a3\0\u08c4\0\u08e5\0\u0906\0\u0927\0\u0948\0\u0969\0\u098a"+
    "\0\u09ab\0\u09cc\0\u09ed\0\u0a0e\0\u0a2f\0\u0a50\0\u0a71\0\u0a92"+
    "\0\102\0\u0ab3\0\u0ad4\0\u0af5\0\41\0\u0b16\0\102\0\u0b37"+
    "\0\u0b58\0\u0b79\0\u0b9a\0\u0bbb\0\u0bdc\0\102\0\u0bfd\0\102"+
    "\0\u0c1e\0\102\0\u0c3f\0\102\0\u0c60\0\u0c81\0\u0ca2\0\u0cc3"+
    "\0\u0ce4\0\u0d05\0\u0d26\0\u0d47\0\102\0\u0d68\0\u0d89\0\u0daa"+
    "\0\u0dcb\0\u0dec\0\u0e0d\0\u0e2e\0\102\0\u0e4f\0\u0e70\0\u0e91"+
    "\0\102\0\u0eb2\0\u0ed3\0\u0ef4\0\u0f15\0\u0f36\0\u0f57\0\u0f78"+
    "\0\u0f99\0\u0fba\0\u0fdb\0\u0ffc\0\u101d\0\u103e\0\u105f\0\u1080"+
    "\0\u10a1\0\u10c2\0\u10e3\0\u1104\0\u1125\0\u1146\0\u1167\0\u1188"+
    "\0\u11a9\0\u11ca\0\u11eb\0\u120c\0\u122d\0\102\0\u124e\0\u126f"+
    "\0\u1290\0\u12b1\0\102\0\u12d2\0\u12f3\0\u1314\0\102\0\u1335"+
    "\0\u1356\0\u1377\0\102\0\102\0\u1398\0\u13b9\0\u13da\0\u13fb"+
    "\0\102\0\102";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\3\1\22\1\3\1\23\1\24\5\3\1\25\1\26"+
    "\2\3\1\27\2\2\42\0\2\3\3\0\30\3\5\0"+
    "\1\4\41\0\1\5\36\0\2\3\3\0\1\3\1\30"+
    "\26\3\4\0\2\3\3\0\5\3\1\31\2\3\1\32"+
    "\17\3\4\0\2\3\3\0\1\3\1\33\26\3\4\0"+
    "\2\3\3\0\15\3\1\34\4\3\1\35\5\3\4\0"+
    "\2\3\3\0\1\3\1\36\1\3\1\37\2\3\1\40"+
    "\21\3\4\0\2\3\3\0\1\3\1\41\26\3\4\0"+
    "\2\3\3\0\5\3\1\42\22\3\4\0\2\3\3\0"+
    "\6\3\1\43\21\3\4\0\2\3\3\0\3\3\1\44"+
    "\24\3\4\0\2\3\3\0\6\3\1\45\3\3\1\46"+
    "\1\3\1\47\13\3\4\0\2\3\3\0\6\3\1\50"+
    "\21\3\4\0\2\3\3\0\1\3\1\51\10\3\1\52"+
    "\15\3\4\0\2\3\3\0\11\3\1\53\16\3\4\0"+
    "\2\3\3\0\1\3\1\54\26\3\4\0\2\3\3\0"+
    "\6\3\1\55\21\3\42\0\1\56\2\0\2\3\3\0"+
    "\2\3\1\57\25\3\4\0\2\3\3\0\1\3\1\60"+
    "\26\3\4\0\2\3\3\0\12\3\1\61\15\3\4\0"+
    "\2\3\3\0\24\3\1\62\3\3\4\0\2\3\3\0"+
    "\1\3\1\63\26\3\4\0\2\3\3\0\7\3\1\64"+
    "\20\3\4\0\2\3\3\0\6\3\1\65\6\3\1\66"+
    "\12\3\4\0\2\3\3\0\5\3\1\57\7\3\1\67"+
    "\5\3\1\70\4\3\4\0\2\3\3\0\5\3\1\71"+
    "\22\3\4\0\2\3\3\0\1\72\27\3\4\0\2\3"+
    "\3\0\6\3\1\73\4\3\1\74\14\3\4\0\2\3"+
    "\3\0\11\3\1\75\16\3\4\0\2\3\3\0\5\3"+
    "\1\76\22\3\4\0\2\3\3\0\7\3\1\77\20\3"+
    "\4\0\2\3\3\0\5\3\1\100\22\3\4\0\2\3"+
    "\3\0\7\3\1\101\20\3\4\0\2\3\3\0\16\3"+
    "\1\102\11\3\4\0\2\3\3\0\5\3\1\103\22\3"+
    "\4\0\2\3\3\0\22\3\1\104\5\3\4\0\2\3"+
    "\3\0\5\3\1\105\22\3\4\0\2\3\3\0\7\3"+
    "\1\106\20\3\5\0\1\107\37\0\2\3\3\0\3\3"+
    "\1\53\24\3\4\0\2\3\3\0\25\3\1\110\2\3"+
    "\4\0\2\3\3\0\3\3\1\111\24\3\4\0\2\3"+
    "\3\0\6\3\1\112\21\3\4\0\2\3\3\0\10\3"+
    "\1\113\17\3\4\0\2\3\3\0\1\3\1\114\26\3"+
    "\4\0\2\3\3\0\5\3\1\115\22\3\4\0\2\3"+
    "\3\0\1\3\1\116\26\3\4\0\2\3\3\0\14\3"+
    "\1\117\13\3\4\0\2\3\3\0\14\3\1\120\13\3"+
    "\4\0\2\3\3\0\6\3\1\121\21\3\4\0\2\3"+
    "\3\0\7\3\1\122\20\3\4\0\2\3\3\0\7\3"+
    "\1\123\20\3\4\0\2\3\3\0\6\3\1\124\21\3"+
    "\4\0\2\3\3\0\3\3\1\125\24\3\4\0\2\3"+
    "\3\0\2\3\1\126\25\3\4\0\2\3\3\0\13\3"+
    "\1\127\14\3\4\0\2\3\3\0\13\3\1\130\14\3"+
    "\4\0\2\3\3\0\14\3\1\131\13\3\4\0\2\3"+
    "\3\0\1\3\1\132\26\3\4\0\2\3\3\0\3\3"+
    "\1\133\24\3\4\0\2\3\3\0\7\3\1\134\20\3"+
    "\5\0\1\107\35\0\1\135\1\0\2\3\3\0\1\3"+
    "\1\136\26\3\4\0\2\3\3\0\17\3\1\137\10\3"+
    "\4\0\2\3\3\0\7\3\1\140\20\3\4\0\2\3"+
    "\3\0\5\3\1\141\22\3\4\0\2\3\3\0\7\3"+
    "\1\142\20\3\4\0\2\3\3\0\13\3\1\143\14\3"+
    "\4\0\2\3\3\0\14\3\1\144\13\3\4\0\2\3"+
    "\3\0\7\3\1\145\20\3\4\0\2\3\3\0\7\3"+
    "\1\145\5\3\1\146\12\3\4\0\2\3\3\0\17\3"+
    "\1\53\10\3\4\0\2\3\3\0\10\3\1\147\17\3"+
    "\4\0\2\3\3\0\6\3\1\150\21\3\4\0\2\3"+
    "\3\0\13\3\1\151\14\3\4\0\2\3\3\0\7\3"+
    "\1\152\20\3\4\0\2\3\3\0\6\3\1\125\21\3"+
    "\4\0\2\3\3\0\14\3\1\153\13\3\4\0\2\3"+
    "\3\0\14\3\1\154\13\3\4\0\2\3\3\0\7\3"+
    "\1\155\20\3\4\0\2\3\3\0\17\3\1\156\10\3"+
    "\4\0\2\3\3\0\3\3\1\157\24\3\4\0\2\3"+
    "\3\0\3\3\1\160\24\3\4\0\2\3\3\0\6\3"+
    "\1\161\21\3\4\0\2\3\3\0\3\3\1\162\24\3"+
    "\4\0\2\3\3\0\20\3\1\163\7\3\4\0\2\3"+
    "\3\0\7\3\1\164\20\3\4\0\2\3\3\0\5\3"+
    "\1\165\22\3\4\0\2\3\3\0\20\3\1\166\7\3"+
    "\4\0\2\3\3\0\1\3\1\57\26\3\4\0\2\3"+
    "\3\0\1\3\1\167\26\3\4\0\2\3\3\0\15\3"+
    "\1\53\12\3\4\0\2\3\3\0\20\3\1\170\7\3"+
    "\4\0\2\3\3\0\1\3\1\171\26\3\4\0\2\3"+
    "\3\0\7\3\1\172\20\3\4\0\2\3\3\0\7\3"+
    "\1\173\20\3\4\0\2\3\3\0\5\3\1\174\22\3"+
    "\4\0\2\3\3\0\7\3\1\175\20\3\4\0\2\3"+
    "\3\0\4\3\1\176\23\3\4\0\2\3\3\0\3\3"+
    "\1\177\24\3\4\0\2\3\3\0\1\3\1\200\26\3"+
    "\4\0\2\3\3\0\7\3\1\201\20\3\4\0\2\3"+
    "\3\0\5\3\1\202\22\3\4\0\2\3\3\0\27\3"+
    "\1\203\4\0\2\3\3\0\20\3\1\204\7\3\4\0"+
    "\2\3\3\0\20\3\1\205\7\3\4\0\2\3\3\0"+
    "\13\3\1\206\14\3\4\0\2\3\3\0\1\3\1\207"+
    "\26\3\4\0\2\3\3\0\15\3\1\210\12\3\4\0"+
    "\2\3\3\0\10\3\1\32\17\3\4\0\2\3\3\0"+
    "\1\3\1\211\26\3\4\0\2\3\3\0\3\3\1\212"+
    "\24\3\4\0\2\3\3\0\4\3\1\213\23\3\4\0"+
    "\2\3\3\0\21\3\1\214\1\215\5\3\4\0\2\3"+
    "\3\0\6\3\1\137\21\3\4\0\2\3\3\0\15\3"+
    "\1\216\12\3\4\0\2\3\3\0\20\3\1\217\7\3"+
    "\4\0\2\3\3\0\1\220\27\3\4\0\2\3\3\0"+
    "\7\3\1\221\20\3\4\0\2\3\3\0\1\3\1\222"+
    "\26\3\4\0\2\3\3\0\12\3\1\223\15\3\4\0"+
    "\2\3\3\0\17\3\1\224\10\3\4\0\2\3\3\0"+
    "\1\3\1\225\26\3\4\0\2\3\3\0\21\3\1\226"+
    "\6\3\4\0\2\3\3\0\6\3\1\227\21\3\4\0"+
    "\2\3\3\0\20\3\1\230\7\3\4\0\2\3\3\0"+
    "\15\3\1\231\12\3\4\0\2\3\3\0\6\3\1\232"+
    "\21\3\4\0\2\3\3\0\14\3\1\233\13\3\4\0"+
    "\2\3\3\0\14\3\1\234\13\3\4\0\2\3\3\0"+
    "\12\3\1\235\15\3\4\0\2\3\3\0\17\3\1\236"+
    "\10\3\4\0\2\3\3\0\22\3\1\237\5\3\4\0"+
    "\2\3\3\0\1\3\1\240\26\3\4\0\2\3\3\0"+
    "\10\3\1\241\17\3\4\0\2\3\3\0\26\3\1\242"+
    "\1\3\4\0\2\3\3\0\5\3\1\243\22\3\4\0"+
    "\2\3\3\0\10\3\1\244\17\3\4\0\2\3\3\0"+
    "\17\3\1\245\10\3\4\0\2\3\3\0\14\3\1\246"+
    "\13\3\4\0\2\3\3\0\14\3\1\247\13\3\4\0"+
    "\2\3\3\0\12\3\1\250\15\3\4\0\2\3\3\0"+
    "\3\3\1\251\24\3\4\0\2\3\3\0\14\3\1\252"+
    "\13\3\4\0\2\3\3\0\5\3\1\253\22\3\4\0"+
    "\2\3\3\0\6\3\1\254\21\3\4\0\2\3\3\0"+
    "\5\3\1\255\22\3\4\0\2\3\3\0\26\3\1\256"+
    "\1\3\4\0\2\3\3\0\2\3\1\257\25\3\4\0"+
    "\2\3\3\0\12\3\1\260\15\3\4\0\2\3\3\0"+
    "\14\3\1\261\13\3\4\0\2\3\3\0\6\3\1\262"+
    "\21\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5148];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\2\11\46\1\1\0\30\1\1\0"+
    "\25\1\1\11\125\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 96) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 6: 
          { lexeme=yytext(); return Comillas;
          }
        case 27: break;
        case 10: 
          { lexeme=yytext(); return P_coma;
          }
        case 28: break;
        case 24: 
          { lexeme=yytext(); return Llave_a;
          }
        case 29: break;
        case 8: 
          { lexeme=yytext(); return Suma;
          }
        case 30: break;
        case 16: 
          { lexeme=yytext(); return Cadena;
          }
        case 31: break;
        case 14: 
          { lexeme=yytext(); return Division;
          }
        case 32: break;
        case 5: 
          { return Linea;
          }
        case 33: break;
        case 15: 
          { lexeme=yytext(); return Op_booleano;
          }
        case 34: break;
        case 12: 
          { lexeme=yytext(); return Op_relacional;
          }
        case 35: break;
        case 17: 
          { lexeme=yytext(); return If;
          }
        case 36: break;
        case 23: 
          { lexeme=yytext(); return Parentesis_c;
          }
        case 37: break;
        case 18: 
          { lexeme=yytext(); return Igual;
          }
        case 38: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 39: break;
        case 20: 
          { lexeme=yytext(); return For;
          }
        case 40: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 41: break;
        case 19: 
          { lexeme=yytext(); return Do;
          }
        case 42: break;
        case 9: 
          { lexeme=yytext(); return Multiplicacion;
          }
        case 43: break;
        case 1: 
          { return ERROR;
          }
        case 44: break;
        case 22: 
          { lexeme=yytext(); return Main;
          }
        case 45: break;
        case 4: 
          { /*Ignore*/
          }
        case 46: break;
        case 25: 
          { lexeme=yytext(); return While;
          }
        case 47: break;
        case 21: 
          { lexeme=yytext(); return Parentesis_a;
          }
        case 48: break;
        case 7: 
          { lexeme=yytext(); return T_dato;
          }
        case 49: break;
        case 26: 
          { lexeme=yytext(); return Llave_c;
          }
        case 50: break;
        case 13: 
          { lexeme=yytext(); return Resta;
          }
        case 51: break;
        case 11: 
          { lexeme=yytext(); return Else;
          }
        case 52: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
